server:
  port: 5280

allowed:
  origins: '*'

github:
  authBaseurl: https://github.com
  baseUrl: https://api.github.com
  clientSecret: 4e0fc0db14e085c497eafa0c2903bb5eff153442
  clientId: 767df7b1cb645c1d0b51
  scope: repo

